Verify lhctl can reach api

diff --git a/kube-merit-updater b/kube-merit-updater
--- a/kube-merit-updater
+++ b/kube-merit-updater
@@ -97,6 +97,12 @@ else
 fi
 export HTTP_PROXY=${HTTP_PROXY}
 
+## Verify lhctl can reach api
+if ! lhctl --context=${lh_context} get volume > /dev/null; then
+  echo "lhctl can't reach api"
+  exit 1
+fi
+
 ### Validation
 if [[ -z "${kube_context}" ]]; then
   usage
